import favicon from '@/assets/favicon.ico';

export function Meta() {
  return (
    <head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={favicon} />
    </head>
  );
}
